### ISSUE TITLE
[FEAT] : 커뮤니티 메인 화면

### ISSUE THREAD

**Issue by ehgus0526** [Team-GAJI/GAJI-Front#10]
### Feature Issue
커뮤니티 메인 화면 레이아웃 구현

### To-do
- [x] 커뮤니티 홈 화면
- [x] 프로젝트 메인 화면
- [x] 질문 메인 화면
- [x] 블로그 메인 화면
