### ISSUE TITLE
[FEAT] : 게시글 쓰기 레이아웃

### ISSUE THREAD

**Issue by ehgus0526** [Team-GAJI/GAJI-Front#17]
### Feature Issue
게시글 쓰기 레이아웃

### To-do
- [x] 헤더
- [x] 카테고리 및 해시태그 버튼
- [x] 게시글 제목
- [x] 툴바 레이아웃 및 기능
- [x] 작성칸 레이아웃 및 마크다운 기능
- [x] 글자 수 확인 및 제한 기능
- [x] 업로드 버튼
