### ISSUE TITLE
[FEAT] : 로그인 화면 수정 및 기능 구현

### ISSUE THREAD

**Issue by jiminseong** [Team-GAJI/GAJI-Front#18]
### To-do

- [x] 로그인 헤더 제거
- [x] 회원가입 및 약관 동의
- [x] 닉네임 모달
- [x] 구글 Redirect 구현
