### ISSUE TITLE
[FEAT] : 마이페이지 기능 구현

### ISSUE THREAD

**Issue by jiminseong** [Team-GAJI/GAJI-Front#19]
### Feature Issue

마이페이지 기능 구현

### To-do

- [x] 페이지 전체 버튼시 해당 화면 기능
- [x] 닉네임 수정 기능
- [x] 현재, 이전 스터디룸 스크롤 기능
- [x] 마케팅 수신 모달 구현
- [x] 일정 추가 기능 구현
- [x] 내가 쓴글 라우팅 버튼 구현
- [x] 내가 쓴 글 무한 스크롤 구현
- [x] 반응형 전환
