### ISSUE TITLE
[FEAT] : 전역 상태, Axios 인스턴스 세팅

### ISSUE THREAD

**Issue by jiminseong** [Team-GAJI/GAJI-Front#20]
### Feature Issue
전역 상태 세팅(헤더,로그인)

### To-do

- [x] 전역 상태 Redux 세팅 - 페이지별 헤더
- [x] 전역 상태 Redux 세팅 - 로그인
- [x] Axios 인스턴스 세팅
