### ISSUE TITLE
[FEAT] : 커뮤니티 관련 기능 구현

### ISSUE THREAD

**Issue by ehgus0526** [Team-GAJI/GAJI-Front#31]
### Feature Issue
커뮤니티 관련 기능 구현

### To-do
- [x] 게시글 미리보기 더미 데이터로 불러오기
- [x] 게시글 미리보기 무한 스크롤 기능
- [x] 게시글 상태에 따라 상태부분 색상 변경
