### ISSUE TITLE
[FEAT] 커뮤니티 관련 레이아웃 수정

### ISSUE THREAD

**Issue by ehgus0526** [Team-GAJI/GAJI-Front#43]
### Feature Issue
커뮤니티 관련 레이아웃 수정

### To-do
- [x] 커뮤니티 헤더 수정
- [x] HOT 게시물 레이아웃 수정
- [x] HOT 게시물 더미데이터로 받아오기
- [x] 메인 검색창 레이아웃 수정
- [x] 필터, 작성 버튼 및 가로선 수정
- [ ] 필터 기능 구현
- [x] 블로그 미리보기 오버 시 반응 구현
- [x] 게시글 작성 해시태그 입력 기능
- [ ] 게시글 작성  textarea 자동 크기 조정
- [x] 게시글 보기 내용 외곽선 제거 및 링크임베드 숨기기
- [x] 게시글 보기 댓글 더미데이터로 받아오기
- [x] 게시글 보기 댓글 무한 스크롤
