### ISSUE TITLE
[FEAT] 스터디 모집 페이지 구현

### ISSUE THREAD

**Issue by ehgus0526** [Team-GAJI/GAJI-Front#59]
### Feature Issue
스터디 모집 페이지 구현

### To-do
- [ ] 스터디 메인페이지 구현
- [ ] 스터디 작성페이지 구현
- [ ] 스터디 상세페이지 구현
