### ISSUE TITLE
[OTHER] 영상 준비용 작업

### ISSUE THREAD

**Issue by jiminseong** [Team-GAJI/GAJI-Front#61]
### Feature Issue
제출용 영상용 체크 

### To-do
아래 해당사항 구현 확인 
- [x] 로그인 페이지 리다이렉트
- [x] 로그아웃
- [x] 마이페이지 
- [x] 스터디 둘러보기
- [x] 스터디 모집
- [x] 스터디 상세정보
- [x] 스터디룸
- [x] 스터디 관리
- [x] 주차별 스터디 관리
- [x] 커뮤니티
- [x] 커뮤니티 글쓰기
- [x] 커뮤니티 글조회
- [x] 트러블 슈팅 페이지
- [x] 트러블 슈팅 등록
