### ISSUE TITLE
[FEAT] 스터디룸 메인 페이지 기능 및 API

### ISSUE THREAD

**Issue by jiminseong** [Team-GAJI/GAJI-Front#66]
### Feature Issue
 스터디룸 메인 페이지 기능 및 API

### To-do
- [x] 마이페이지 상단 헤더 수정
- [x] 스터디룸 UI 수정
- [x] 스터디룸 반응형 완성
- [x] 스터디룸 공지 등록 API
- [x] 스터디룸 주차 정보 weeks 불러오기 API
- [x] 스터디룸 게시글 작성 UI
- [x] 스터디룸  게시글 작성 API
- [x] 스터디룸 게시글 불러오기 API
- [x] 스터디룸 게시글 미리보기 API
- [ ] {studyinfo, roomId} => roomId로만 studyroom페이지 넘어가도록 
- [ ] 스터디룸 게시글 댓글 작성, 수정 API
- [ ] 스터디룸 게시글 댓글 불러오기 API
- [ ] 주차별 제목, 설명 , 주차 날짜 불러오기 API
- [ ] 스터디룸 주차별 버튼 기능
- [ ] 주차별 스터디원 달성도 불러오기 API
- [ ] 스터디룸 설명 입력 API
- [ ] 스터디룸 과제 불러오기 API
- [ ] 스터디룸 과제 완료 API
- [ ] 주차별 나의 이번주 과제 불러오기 API
- [ ] 스터디룸 주차별 게시글 조회 API
- [ ] 스터디 가지기 API
- [ ] 공지사항 조회 API -> 코드 개편 필요
