### ISSUE TITLE
[FEAT] 트러블슈팅 게시판 최종수정

### ISSUE THREAD

**Issue by jeon99yu** [Team-GAJI/GAJI-Front#67]
### To-do

- [x] Item 콘텐트 커서반응추가
- [x] Item 콘텐트 상단 댓글 아이콘 및 개수 표시
- [x] 트러블슈팅 등록버튼 폰트 미적용해결
- [x] 스터디룸공지 최상단 테두리효과 적용

**Comment by jeon99yu** [comment]
![image](https://github.com/user-attachments/assets/adcb1a41-2dc3-454f-bc7a-fccd49f758c4)

**Comment by jeon99yu** [comment]
![image](https://github.com/user-attachments/assets/1607f6c5-e3c6-4d8c-a236-8d1a4458fe1b)
