### ISSUE TITLE
[CSS] 반응형 구현

### ISSUE THREAD

**Issue by jiminseong** [Team-GAJI/GAJI-Front#80]
### Feature Issue
모든 페이지 반응형 구현

### To-do

- [x] 메인 페이지
- [x] 커뮤니티 페이지
- [x] 커뮤니티 작성페이지
- [x] 작성 컴포넌트 
- [x] 마이페이지
- [x] 마이페이지 스크롤시 버튼 색변함
- [x] 로그인 페이지
- [x] 스터디 페이지
- [x] 커뮤니티 게시글 상세 조회 페이지
- [x] 스터디 만들기 페이지
- [x] 스터디 관리 페이지
- [x] 스터디 주차별 관리 페이지
- [x] 스터디 공지
- [x] 스터디 공지 등록페이지
- [x] 스터디 트러블 슈팅 리스트
- [x] 스터디 트러블 슈팅 등록 페이지
- [x] 스터디 게시글 상세 조회
- [x] 커뮤니티 게시글 모달
- [x] 작성하기 버튼 모바일
- [x] 스터디 카테고리(더보기 누를시에)
- [x] 스터디룸 주차별 버튼 -> 스터디 관리 페이지 처럼
- [x] 스터디룸, 트러블슈팅 게시글 상세 조회 페이지(추후)
- [ ] 공용 헤더
