### ISSUE TITLE
[API] 마이페이지 API

### ISSUE THREAD

**Issue by jiminseong** [Team-GAJI/GAJI-Front#94]
### Feature Issue
마이페이지 API

### To-do

- [x] 유저 정보 API
- [x] 현재 스터디 리스트 조회
- [x] 과거 스터디 리스트 조회
- [ ] 현재 나의 일정
- [ ] 내 게시글 조회
